### PR TITLE
v4.1.1

### LINKED ISSUE #33: Axios version update
Can you move to the latest version of axios. Security checks are failing

`Cross-site Request Forgery (CSRF) [High Severity][https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459] in axios@0.21.4
    introduced by @pixelbin/admin@4.1.0 > axios@0.21.4
  This issue was fixed in versions: 0.28.0, 1.6.0`

### PR DESCRIPTION
**Pull request by krithik-fynd**
Fixes #33

### CODE REVIEW

File: sdk/common/AxiosHelper.js [hunk 1]
```diff
@@ -1,11 +1,37 @@
...
+ * @param {string} baseURL The base URL
+ * @param {string} relativeURL The relative URL
+ * @returns {string} The combined URL
+ */
+function combineURLs(baseURL, relativeURL) {
+    return relativeURL
+        ? baseURL.replace(/\/+$/, "") + "/" + relativeURL.replace(/^\/+/, "")
+        : baseURL;
+}
+
```
Comment (pixelbin-dev) [inline sdk/common/AxiosHelper.js:34]: Why have we added this? 
Doesn't look like its being used somewhere.

Comment (krithik-fynd) [reply sdk/common/AxiosHelper.js:34]: It is used here https://github.com/pixelbin-io/pixelbin-js-admin/blob/b3f3503ae8623c63889cb3049b11abe24e6825d2/sdk/common/AxiosHelper.js#L94

Added for compatibility if and when we require signature generation again.

**Review by pixelbin-dev — APPROVED** [review]
